global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "cadvisor"
    static_configs:
      - targets: ["localhost:8080"]

  - job_name: "gpu_exporter"
    static_configs:
      - targets: ["localhost:9400"]

  - job_name: "network_topology"
    static_configs:
      - targets: ["localhost:9500"]

  - job_name: "gpu_topology"
    static_configs:
      - targets: ["localhost:9600"]
